apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod #name of pod
  labels:
    env: development
    app: nginx-app
    tier: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx