apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 #This is port at which nginx listens. Nginx is running in pod.
      targetPort: 80 #Port on service itself
      nodePort: 30004 #This can be anywhere between 30000 - 32767
                      #This is the port on which app can be accessible.
  selector:
    app: myapp #We need to bind service to POD. So picked this from POD label at currnt folder\deployments\deployment.yml
      